name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "script/build.sh"
